language: ruby
rvm:
 - "2.2.2"
 - "2.2.3"
 - "2.2.4"
 - "2.3.0"

services:
  - postgresql

before_script:
  - psql -c 'create database nightlycoffee_test;' -U postgres
  - npm install -g bower
  - bower install

language: node_js
node_js:
  - "5.4.0"
before_script:  
  - npm install -g bower
  - bower install